version: '3.8'

services:
  api-service:
    build: ./api-service
    # ports:
    #   - "8000:8000"
    # cant scale with host port mapping
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    depends_on:
      db-service:
        condition: service_healthy
      transcript-service:
        condition: service_healthy
      llm-service:
        condition: service_healthy
    environment:
      DB_SERVICE_URL: http://db-service:8000
      LLM_SERVICE_URL: http://llm-service:8000
      TRANSCRIPT_SERVICE_URL: http://transcript-service:8000
      # environment:
      # - LLM_SERVICE_BASE=http://llm-service:8001
  db-service:
    build: ./db-service
    # container_name: db-service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://summaryze:summaryze@postgres-db:5432/summaries
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  transcript-service:
    build: ./transcript-service
    ports:
      - "8002:8000"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  llm-service:
    build: ./llm-service
    ports:
      - "8003:8000"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  postgres-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: summaries
      POSTGRES_USER: summaryze
      POSTGRES_PASSWORD: summaryze
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "summaryze",
          "-d",
          "summaries"
        ]
      interval: 3s
      timeout: 2s
      retries: 10
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: api-gateway
    depends_on:
      api-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
networks:
  default:
    driver: bridge

volumes:
  postgres_data:
